# Site settings
site: 提笔忘字
title: 提笔忘字 - 我的博客
keywords: 提笔忘字, 博客
description: >-
  正是江南好风景，落花时节又逢君。
lang: zh-CN
timezone: Asia/Shanghai

# Author settings
author:
  name: Xie Ziyao
  bio: CSer @NJU <br> Open Source @LTP <br> Computer Engineer @Tencent
  picture: assets/images/profile.jpg
  twitter: XieZiyao # twitter username
  github: ziyaoxie # github username
  linkedin: xieziyao # linkedin username
  email: ziyaoxie@outlook.com # email address

gitalk:
  enable: true # 总开关，控制gitalk功能是否开启
  clientId: 084594950ca06b86a714
  clientSecret: 97f004b4b080ac66be952afa032acb4dd39aa4eb
  repo: ziyaoxie.github.io
  owner: ziyaoxie
  admin: ziyaoxie
#  distractionFreeMode: true # 若设置为true，则当在评论框输入时，周围区域会变暗

# URL settings
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
url: "https://imx.ink" # Domain Name of host. [username].github.io for github pages
permalink: pretty

# 百度统计
baidu_tmid: 7236cce7205c66e3b7b7890fdcd6611f

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false